from whole_blur import WholeBlur
from blurred_context import BlurredContext
from unconventional_size import UnconventionalSize
from low_resolution import LowResolution
from pattern_detection import PatternDetection
from exposure import Exposure
from small_object import ObjectTooSmall
from multiple_salient_regions import MultipleSalientRegions
from hdr import HDR
from posterized_image import Posterized
from cross_processed import CrossProcessed
from framed import Framed
