from whole_blur import WholeBlur
from blurred_context import BlurredContext
from unconventional_size import UnconventionalSize
from low_resolution import LowResolution
from pattern_detection import PatternDetection
