Contents:

.. toctree::
   :maxdepth: 2


API Documentation
-----------------

.. toctree::
   :maxdepth: 2

   api

Installation
------------

.. toctree::
   :maxdepth: 2

   installation

Testing Documentation
---------------------

.. toctree::
   :maxdepth: 2

   testing

Architecture Documentation
--------------------------

.. toctree::
   :maxdepth: 2

   architecture

Training Documentation
----------------------

.. toctree::
   :maxdepth: 2

   training
